// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Id2Cg3CLvCz7-SzgGTFVzHjIXwV-jYQ',
    appId: '1:765922253113:web:1fa870cc800932433830e8',
    messagingSenderId: '765922253113',
    projectId: 'chat2-f0a63',
    authDomain: 'chat2-f0a63.firebaseapp.com',
    storageBucket: 'chat2-f0a63.appspot.com',
    measurementId: 'G-QQHNMHSXZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9mQnnaRl4Dnt4BSJWk-rM8XLTYnp5_Cw',
    appId: '1:765922253113:android:5974d3948c190e6c3830e8',
    messagingSenderId: '765922253113',
    projectId: 'chat2-f0a63',
    storageBucket: 'chat2-f0a63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92bNO7noKACOMBeoGEXD_1uUyyag8mX0',
    appId: '1:765922253113:ios:0c284d7949dd0f0e3830e8',
    messagingSenderId: '765922253113',
    projectId: 'chat2-f0a63',
    storageBucket: 'chat2-f0a63.appspot.com',
    iosClientId: '765922253113-p23uqp9s797r5cmldtqhtl2pc5dreci9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC92bNO7noKACOMBeoGEXD_1uUyyag8mX0',
    appId: '1:765922253113:ios:b64b85228b75fd733830e8',
    messagingSenderId: '765922253113',
    projectId: 'chat2-f0a63',
    storageBucket: 'chat2-f0a63.appspot.com',
    iosClientId: '765922253113-c3dj6f9rllsaeof81m6it49hr5lmhua6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
